#language: java
#sudo: false
#
#matrix:
#  include:
#    #==============================
#    #
#    #     osx 
#    #
#    #==============================
#
#    - os: osx
#      compiler: javac
#      osx_image: xcode7.3
#
#    - os: osx
#      compiler: javac
#      osx_image: xcode8
#
#    - os: osx
#      compiler: javac
#      osx_image: xcode8.3
#
#    - os: osx
#      compiler: javac
#      osx_image: xcode9
#
#    - os: osx
#      compiler: javac
#      osx_image: xcode9.1
#
#    - os: osx
#      compiler: javac
#      osx_image: xcode9.2
#
#    - os: osx
#      compiler: javac
#      osx_image: xcode9.3
#
#    - os: osx
#      compiler: javac
#      osx_image: xcode9.4
#
#    - os: osx
#      compiler: javac
#      osx_image: xcode10
#
#    #==============================
#    #
#    #     linux 
#    #
#    #==============================
#    
#    - os: linux
#      compiler: javac
#
#before_install:
#  - eval
#
#script:
#  - TODO