language: java
sudo: false

matrix:
  include:

    #==============================
    #
    #     linux oracle
    #
    #==============================

    - os: linux
      compiler: javac
      jdk: oraclejdk9

    - os: linux
      compiler: javac
      jdk: oraclejdk11

    #==============================
    #
    #     linux open
    #
    #==============================

    - os: linux
      compiler: javac
      jdk: openjdk8

    - os: linux
      compiler: javac
      jdk: openjdk9

    - os: linux
      compiler: javac
      jdk: openjdk10

    - os: linux
      compiler: javac
      jdk: openjdk11

before_install:
  - eval
  - mkdir build

script:
  - javac -cp "VoldBench/lib/voldemort/*:VoldBench/lib/sql/*" ./VoldBench/src/Activity/Option.java -d build
  - javac -cp "VoldBench/lib/voldemort/*:VoldBench/lib/sql/*:build" ./VoldBench/src/Benchmark/* -d build
  - javac -cp "VoldBench/lib/voldemort/*:VoldBench/lib/sql/*:build" ./VoldBench/src/Activity/Main.java -d build
  #- java -cp "./build:./VoldBench/lib/voldemort/*:./VoldBench/lib/sql/*" Activity.Main
